// SPDX-License-Identifier: MIT
/**
 * FastAPI hello — 5 files. A minimal ASGI app exposing a single
 * `/hello` route, a `requirements.txt` so `pip install -r` works out
 * of the box, a `.gitignore` covering Python build artifacts and the
 * `.venv/` directory (fold E), and a README. The entry file is
 * `app/main.py` so the user lands on the route definition.
 *
 * Each Python file generated by this template carries its own
 * `# SPDX-License-Identifier: MIT` header (fold F) so the structural
 * test that greps every emitted file content for a license line passes.
 */

import type { ProjectTemplateV1 } from '../../../shared/projectTemplate';

export const fastapiHelloTemplate: ProjectTemplateV1 = {
  schemaVersion: 1,
  id: 'fastapi-hello',
  labelKey: 'emptyState.projectTemplates.fastapiHello.label',
  descriptionKey: 'emptyState.projectTemplates.fastapiHello.description',
  language: 'python',
  entryFile: 'app/main.py',
  files: [
    {
      relPath: 'app/main.py',
      content: `# SPDX-License-Identifier: MIT
from fastapi import FastAPI

app = FastAPI()


@app.get("/hello")
def hello():
    return {"message": "Hello from Lingua + FastAPI!"}
`,
    },
    {
      relPath: 'app/__init__.py',
      content: `# SPDX-License-Identifier: MIT
`,
    },
    {
      relPath: 'requirements.txt',
      content: `# SPDX-License-Identifier: MIT
fastapi>=0.110
uvicorn[standard]>=0.27
`,
    },
    {
      relPath: '.gitignore',
      content: `# SPDX-License-Identifier: MIT
__pycache__/
*.pyc
*.pyo
.venv/
.env
.env.local
.pytest_cache/
.mypy_cache/
`,
    },
    {
      relPath: 'README.md',
      content: `<!-- SPDX-License-Identifier: MIT -->
# FastAPI hello

Minimal ASGI service scaffolded by Lingua.

## Run

\`\`\`
python -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
uvicorn app.main:app --reload
\`\`\`

Then visit http://localhost:8000/hello.
`,
    },
  ],
  dependencies: {
    pip: ['fastapi', 'uvicorn'],
  },
  runCommand: 'uvicorn app.main:app --reload',
  license: 'MIT',
};
