/**
 * Stable public facade for Lingua telemetry.
 *
 * Responsibility modules live under ./telemetry. Keep application imports on
 * this facade so the internal split can evolve without call-site churn.
 */

export { BOOT_DURATION_BUCKETS, BOOT_PHASES, bucketBootDuration } from './bootTelemetry';
export type { BootDurationBucket, BootPhase } from './bootTelemetry';
export { TELEMETRY_EVENTS } from './telemetry/catalog';
export type { TelemetryEventName } from './telemetry/catalog';
export {
  BOOTSTRAP_FAILURE_REASONS,
  CONSOLE_RICH_KIND_BUCKETS,
  RICH_MEDIA_REJECTED_KINDS,
  RICH_MEDIA_REJECTED_REASONS,
  RUBY_DISPATCHED_MODE_VALUES,
  RUBY_SPAWN_BUCKETS,
  RUBY_RUNTIME_PREFERENCE_VALUES,
  FS_DIRECTORY_PICKER_UA_BUCKETS,
  CAPSULE_EXPORT_TRIGGERS,
  CAPSULE_BROWSE_SURFACES,
  CAPSULE_SIZE_BUCKETS,
  IMAGE_CLIPBOARD_PASTE_STATUSES,
  CAPSULE_IMPORT_SOURCES,
  CAPSULE_IMPORT_STATUSES,
  IMPORTER_IDS_SET,
  IMPORT_STATUSES_SET,
  NOTEBOOK_WARNING_KINDS_SET,
  RECIPE_RUN_STATUSES_SET,
  NOTEBOOK_CELL_STATUSES_SET,
  NOTEBOOK_CELL_LANGUAGES_SET,
  NOTEBOOK_EXPORT_FORMATS_SET,
  LANGUAGE_SCORECARD_SURFACES,
  LANGUAGE_SCORECARD_PLATFORMS,
  SHARE_CREATE_TRIGGERS,
  SHARE_CREATE_STATUSES,
  SHARE_OPEN_STATUSES,
  SHARE_SIZE_BUCKETS_SET,
  ONBOARDING_TOAST_STAGES,
  ONBOARDING_DISMISS_MODES,
  PRIVACY_DASHBOARD_SURFACES,
  OUTPUT_ORIGIN_SURFACES,
  GIT_LAYER_REPO_STATES,
  REVEAL_IN_SC_TARGETS,
  EXTERNAL_RELOAD_MODES,
  TEMPLATE_PROJECT_IDS,
  DEPENDENCY_COUNT_BUCKETS_SET,
  PROJECT_BUNDLE_EXPORT_STATUSES,
  PROJECT_BUNDLE_IMPORT_STATUSES,
  PROJECT_BUNDLE_REJECT_REASONS,
  DEPENDENCY_INSTALL_OUTCOMES_SET,
  REPLACE_IN_FILES_SCOPES,
  HTTP_METHODS_SET,
  HTTP_STATUS_BUCKETS_SET,
  SQL_QUERY_STATUSES_SET,
  SQL_STORAGE_MODES_SET,
  SQL_DURATION_BUCKETS_SET,
  SQL_IMPORT_FORMATS_SET,
  SQL_IMPORT_SOURCES_SET,
  PIPELINE_RUN_STATUSES_SET,
  PIPELINE_TEMPLATE_IDS_SET,
  DEPENDENCY_INSTALL_FAILURE_REASONS_SET,
  FS_BLOCKED_FAMILIES,
  SESSION_RESTORE_SOURCES,
  LINT_RULE_IDS,
  LINT_SEVERITIES,
  SMART_PASTE_HANDLERS,
  isSafeToken,
} from './telemetry/valueCatalog';
export { DENY_SUBSTRINGS, redactForTelemetry } from './telemetry/redaction';
export type { RedactionResult } from './telemetry/redaction';
export { bucketDurationMs, bucketOs, createSessionId } from './telemetry/transport';
export type { TelemetryBaseFields, TelemetryEvent } from './telemetry/transport';
